master:
  image: eeacms/jenkins:master
  user: 1000
  ports:
    - "80:8080"
    - "50000:50000"
  volumes_from:
    - data
  links:
    - postfix
  env_file:
    - .secret

worker:
  image: eeacms/jenkins:slave
  user: 1000
  volumes_from:
    - data
  env_file:
    - .secret

centos:
  image: eeacms/jenkins:centos-slave
  user: 1000
  volumes_from:
    - data
  env_file:
    - .secret

debian:
  image: eeacms/jenkins:debian-slave
  user: 1000
  volumes_from:
    - data
  env_file:
    - .secret

ubuntu:
  image: eeacms/jenkins:ubuntu-slave
  user: 1000
  volumes_from:
    - data
  env_file:
    - .secret

postfix:
  image: yorkshirekev/postfix
  entrypoint: ["/bin/bash", "-c", "/startservices.sh $POSTFIX_DOMAIN"]
  env_file:
    - .secret

data:
  build: data
  user: 1000
  volumes:
    - /var/jenkins_home
