master:
  image: eeacms/jenkins-master:2.0
  restart: always
  ports:
  - "80:8080"
  - "50000:50000"
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - master_data
  links:
  - postfix
  env_file:
  - master.env

master_data:
  image: busybox
  volumes:
  - /var/jenkins_home
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home"]

worker:
  image: eeacms/jenkins-slave-eea:2.0
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - worker_data
  env_file:
  - .secret
  - slave.env
  links:
  - postgres

worker_data:
  image: busybox
  volumes:
  - /var/jenkins_home/worker
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home/worker"]

postfix:
  image: eeacms/postfix:eionet
  restart: always
  env_file:
    - .secret
    - postfix.env
  volumes:
    - /etc/localtime:/etc/localtime:ro

postgres:
  image: eeacms/postgres:9.4
  restart: always
  env_file:
  - .secret
  volumes:
  - /etc/localtime:/etc/localtime:ro
