master:
  restart: always
  image: eeacms/jenkins:master
  ports:
    - "80:8080"
    - "50000:50000"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - data
  links:
    - postfix

worker:
  restart: always
  image: eeacms/jenkins:slave
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

centos:
  image: eeacms/jenkins:centos-slave
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

debian:
  image: eeacms/jenkins:debian-slave
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

ubuntu:
  image: eeacms/jenkins:ubuntu-slave
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - data
  env_file:
    - .secret
    - slave.env

postfix:
  restart: always
  image: eeacms/postfix
  env_file:
    - .secret
    - postfix.env
  volumes:
    - /etc/localtime:/etc/localtime:ro

data:
  image: busybox
  volumes:
    - /var/jenkins_home
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home"]
