centos:
  image: eeacms/jenkins:centos-slave
  volumes:
    - /var/jenkins_home:/var/jenkins_home
  env_file:
    - .secret

debian:
  image: eeacms/jenkins:debian-slave
  volumes:
    - /var/jenkins_home:/var/jenkins_home
  env_file:
    - .secret

ubuntu:
  image: eeacms/jenkins:ubuntu-slave
  volumes:
    - /var/jenkins_home:/var/jenkins_home
  env_file:
    - .secret
